name: Publish Gradle Plugins

on:
  push:
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Gradle publish
        run: ./gradlew publish
        env:
          USERNAME: ${{ env.GITHUB_ACTOR }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}